def Main():
    print("\t\t\t\t\t\t\t\t		 ------ HOTEL ROOMS INFO ------")
    print("\t\t\t\t")
    print("\t\t\t\t\t\t\t\tSTANDARD NON-AC")
    print("\t\t\t\t---------------------------------------------------------------")
    print("\t\t\t\tRoom amenities include: 1 Single Bed, Television, Telephone,")
    print("\t\t\t\tDouble-Door Cupboard, 1 Coffee table with 2 sofa, Balcony and")
    print("\t\t\t\tan attached washroom with hot/cold water.\n")
    print("\t\t\t\t\t\t\t\tSTANDARD NON-AC")
    print("\t\t\t\t---------------------------------------------------------------")
    print("\t\t\t\tRoom amenities include: 1 Single Bed, Television, Telephone,")
    print("\t\t\t\tDouble-Door Cupboard, 1 Coffee table with 2 sofa, Balcony and")
    print("\t\t\t\tan attached washroom with hot/cold water + Window/Split AC.\n")
    print("\t\t\t\t\t\t\t\t2-Bed NON-AC")
    print("\t\t\t\t---------------------------------------------------------------")
    print("\t\t\t\tRoom amenities include: 1 Double Bed, Television, Telephone,")
    print("\t\t\t\tDouble-Door Cupboard, 1 Coffee table with 2 sofa, Balcony and")
    print("\t\t\t\tan attached washroom with hot/cold water.\n")
    print("\t\t\t\t\t\t\t\t2 Bed AC")
    print("\t\t\t\t---------------------------------------------------------------")
    print("\t\t\t\tRoom amenities include: 1 Double Bed, Television, Telephone,")
    print("\t\t\t\tDouble-Door Cupboard, 1 Coffee table with 2 sofa, Balcony and")
    print("\t\t\t\tan attached washroom with hot/cold water + Window/Split AC.\n")
    print("\t\t\t\t\t\t\t\t3-Bed NON-AC")
    print("\t\t\t\t---------------------------------------------------------------")
    print("\t\t\t\tRoom amenities include: 1 Double Bed + 1 Single Bed, Television,")
    print("\t\t\t\tTelephone, a Triple-Door Cupboard, 1 Coffee table with 2 sofa, 1")
    print("\t\t\t\tSide table, Balcony with an Accent table with 2 Chair and an")
    print("\t\t\t\tattached washroom with hot/cold water.\n")
    print("\t\t\t\t\t\t\t\t3-Bed AC")
    print("\t\t\t\t---------------------------------------------------------------")
    print("\t\t\t\tRoom amenities include: 1 Double Bed + 1 Single Bed, Television,")
    print("\t\t\t\tTelephone, a Triple-Door Cupboard, 1 Coffee table with 2 sofa, ")
    print("\t\t\t\t1 Side table, Balcony with an Accent table with 2 Chair and an")
    print("\t\t\t\tattached washroom with hot/cold water + Window/Split AC.\n\n")
    print()
    while True:
        n=int(input("\t\t\t\t0-BACK\n\t\t\t ->"))
        if n==0:
            break
        else:
            print("\t\t\t\t\t\t\t\t!!!Invalid Input!!!")
            print("\t\t\t\t\t\t\t\t!!!Try Again!!!")